# Generated by Django 6.0 on 2026-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(help_text='The question the user asked Lilian')),
                ('ai_response', models.TextField(help_text="Lilian's response")),
                ('intent_detected', models.CharField(blank=True, help_text='The intent category detected by the AI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text="Product brand name, e.g., 'High-Grade Diesel'", max_length=255)),
                ('part_number', models.CharField(help_text="Unique part identifier, e.g., 'PD - 100'", max_length=100)),
                ('type', models.CharField(choices=[('petroleum', 'Petroleum'), ('lubricant', 'Lubricant'), ('chemical', 'Chemical'), ('gas', 'Gas'), ('other', 'Other')], help_text="Product category type, e.g., 'Petroleum'", max_length=50)),
                ('usage_rate', models.CharField(help_text="Consumption rate, e.g., '500Liters'", max_length=100)),
                ('batch_number', models.CharField(help_text="Manufacturing batch ID, e.g., 'B-001'", max_length=100)),
                ('shelf_life', models.CharField(help_text="Expected shelf life duration, e.g., '5 years'", max_length=50)),
                ('expiry_date', models.DateField(help_text='Product expiration date')),
                ('company', models.CharField(help_text="Supplier/manufacturer company, e.g., 'Global Fuels Ltd'", max_length=255)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('expired', 'Expired'), ('near_expiry', 'Near Expiry')], default='healthy', help_text='Current product status: healthy, expired, or near_expiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['expiry_date'],
            },
        ),
    ]
