# Generated by Django 6.0 on 2026-03-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationlog',
            name='assistant_name',
            field=models.CharField(default='lilian', help_text="Which AI assistant handled this query (e.g., 'lilian' or 'marie')", max_length=50),
        ),
    ]
