# Generated by Django 6.0 on 2026-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0002_aiconversationlog_assistant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bug', 'Bug / Error'), ('feature', 'Feature Request'), ('question', 'Question'), ('inventory', 'Inventory Issue'), ('marketplace', 'Marketplace Issue'), ('other', 'Other')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
