# Generated by Django 6.0 on 2026-03-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0003_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
