# Generated by Django 6.0 on 2026-03-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0004_alter_supportticket_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='subject',
        ),
    ]
