# Generated by Django 6.0 on 2026-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0005_remove_supportticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='alt_part_number',
            field=models.CharField(blank=True, default='', help_text='Alternate part number', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Running balance or total value', max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(blank=True, default='', help_text="Product condition, e.g., 'New', 'Used'", max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description of the product'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='mil_spec',
            field=models.CharField(blank=True, default='', help_text="Military specification code (e.g., 'MIL-L-23699')", max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='my_part_number',
            field=models.CharField(blank=True, default='', help_text='Internal/custom part number', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes about this item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price of the product', max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='Full product name (may differ from brand)', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Serial number of the item', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Source or supplier name', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uom',
            field=models.CharField(blank=True, default='', help_text="Unit of measure, e.g., 'Gallon', 'Liter'", max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text="Manufacturing batch ID, e.g., 'B-001'", max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, default='', help_text="Product brand name, e.g., 'High-Grade Diesel'", max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='company',
            field=models.CharField(blank=True, default='', help_text="Supplier/manufacturer company, e.g., 'Global Fuels Ltd'", max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='shelf_life',
            field=models.CharField(blank=True, default='', help_text="Expected shelf life duration, e.g., '5 years'", max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='usage_rate',
            field=models.CharField(blank=True, default='', help_text="Consumption rate, e.g., '500Liters'", max_length=100),
        ),
    ]
