# Generated by Django 6.0 on 2026-03-16 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0006_inventoryitem_alt_part_number_inventoryitem_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POLItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pol_type', models.CharField(choices=[('petroleum', 'Petroleum'), ('oil', 'Oil'), ('lubricant', 'Lubricant')], default='petroleum', max_length=20)),
                ('uom', models.CharField(choices=[('QT', 'Quart'), ('OZ', 'Ounce'), ('LB', 'Pound'), ('RL', 'Roll'), ('EA', 'Each'), ('GAL', 'Gallon'), ('ML', 'Millilitre'), ('PT', 'Pint'), ('KT', 'Kit'), ('GM', 'Gram'), ('FT', 'Feet'), ('SQ ST', 'Square Feet'), ('YD', 'Yard'), ('CC', 'Cubic Centimeter')], default='GAL', help_text='Unit of Measurement', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Stock/Availability', max_digits=10)),
                ('shelf_life', models.CharField(help_text='e.g. 5 years', max_length=50)),
                ('expiry', models.DateField()),
                ('expiry_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('near_expiry', 'Near Expiry')], default='active', max_length=20)),
                ('condition', models.CharField(choices=[('new_pol', 'New POL'), ('leftover_pol', 'Leftover POL'), ('opened_pol', 'Opened POL')], default='new_pol', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('expired', 'Expired'), ('low_stock', 'Low Stock')], default='healthy', max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('alt_part_number', models.CharField(blank=True, max_length=50)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=50)),
                ('mil_spec', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pol_images/')),
                ('msds_file', models.FileField(blank=True, null=True, upload_to='msds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pol_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POL Item',
                'verbose_name_plural': 'POL Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
