# Generated by Django 6.0 on 2026-03-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_ai', '0008_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Specific actions taken by admin to resolve the ticket', null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
